### ISSUE TITLE
一点小建议，助您成功

### ISSUE THREAD

**Issue by disksing** [aomoxo/aomoxo-plan#2]
> 爱梦想将会与腾讯公司为邻，推出可以与微信、QQ相媲美，能够广为人们喜爱的新型聊天软件，让人们从使用不同的产品中体验到不同的喜悦；爱梦想也将会与阿里巴巴比肩，推出敢于与淘宝天猫一争高低的网上购物环境，让购物者在互联网上也同样可以实现多样化的选择，能够刚走出一家商场的大门，立刻就可以踏入另一家一样wonderful的购物中心；爱梦想还会走出国门，在全球互联网IT舞台上扮演主角，与谷歌比技术，与亚马逊争市场，与facebook赛创意，让世界各地各种文化背景的消费者都可以享受另一个wonderful公司提供的another choice。

看上去要做的这些APP，需要存储大规模数据， 我们应该想要一款分布式数据库，这里隆重推荐国产分布式数据库TiDB (https://github.com/pingcap/tidb)

TiDB 是一款定位于在线事务处理/在线分析处理（ HTAP: Hybrid Transactional/Analytical Processing）的融合型数据库产品，实现了一键水平伸缩，强一致性的多副本数据安全，分布式事务，实时 OLAP 等重要特性。同时兼容 MySQL 协议和生态，迁移便捷，运维成本极低。

**Comment by fireflyhoo** [comment]
同时推荐一下阿里云的  代金劵  https://www.aliyun.com/minisite/goods?userCode=yinuqud1

**Comment by yoyo837** [comment]
还都一本正经的，😂

**Comment by Rustin-Liu** [comment]
> > 爱梦想将会与腾讯公司为邻，推出可以与微信、QQ相媲美，能够广为人们喜爱的新型聊天软件，让人们从使用不同的产品中体验到不同的喜悦；爱梦想也将会与阿里巴巴比肩，推出敢于与淘宝天猫一争高低的网上购物环境，让购物者在互联网上也同样可以实现多样化的选择，能够刚走出一家商场的大门，立刻就可以踏入另一家一样wonderful的购物中心；爱梦想还会走出国门，在全球互联网IT舞台上扮演主角，与谷歌比技术，与亚马逊争市场，与facebook赛创意，让世界各地各种文化背景的消费者都可以享受另一个wonderful公司提供的another choice。
> 
> 看上去要做的这些APP，需要存储大规模数据， 我们应该想要一款分布式数据库，这里隆重推荐国产分布式数据库TiDB (https://github.com/pingcap/tidb)
> 
> TiDB 是一款定位于在线事务处理/在线分析处理（ HTAP: Hybrid Transactional/Analytical Processing）的融合型数据库产品，实现了一键水平伸缩，强一致性的多副本数据安全，分布式事务，实时 OLAP 等重要特性。同时兼容 MySQL 协议和生态，迁移便捷，运维成本极低。

+ 1，TiDB 你值得拥有！

**Comment by haoxiuwang** [comment]
thanks
