### ISSUE TITLE
一点小建议，祝您成功

### ISSUE THREAD

**Issue by Rustin-Liu** [aomoxo/aomoxo-plan#3]
>爱梦想将会与腾讯公司为邻，推出可以与微信、QQ相媲美，能够广为人们喜爱的新型聊天软件，让人们从使用不同的产品中体验到不同的喜悦；爱梦想也将会与阿里巴巴比肩，推出敢于与淘宝天猫一争高低的网上购物环境，让购物者在互联网上也同样可以实现多样化的选择，能够刚走出一家商场的大门，立刻就可以踏入另一家一样wonderful的购物中心；爱梦想还会走出国门，在全球互联网IT舞台上扮演主角，与谷歌比技术，与亚马逊争市场，与facebook赛创意，让世界各地各种文化背景的消费者都可以享受另一个wonderful公司提供的another choice。

看上去要做的这些APP，需要既美观又体验极好的 UI 设计 ， 我们应该想要一款企业级的 UI 组件库，这里隆重推荐国产 UI 组件库 [antd](https://ant.design/index-cn).

antd 是基于 Ant Design 设计体系的 React UI 组件库，主要用于研发企业级中后台产品。
✨ 特性

    🌈 提炼自企业级中后台产品的交互语言和视觉风格。

    📦 开箱即用的高质量 React 组件。

    🛡 使用 TypeScript 开发，提供完整的类型定义文件。

    ⚙️ 全链路开发和设计工具体系。

    🌍 数十个国际化语言支持。

    🎨 深入每个细节的主题定制能力。

欢迎试用！

**Comment by haoxiuwang** [comment]
thanks

**Comment by afc163** [comment]
+1
