### ISSUE TITLE
一点小建议，祝您成功

### ISSUE THREAD

**Issue by Amour1688** [aomoxo/aomoxo-plan#4]
> 爱梦想将会与腾讯公司为邻，推出可以与微信、QQ相媲美，能够广为人们喜爱的新型聊天软件，让人们从使用不同的产品中体验到不同的喜悦；爱梦想也将会与阿里巴巴比肩，推出敢于与淘宝天猫一争高低的网上购物环境，让购物者在互联网上也同样可以实现多样化的选择，能够刚走出一家商场的大门，立刻就可以踏入另一家一样wonderful的购物中心；爱梦想还会走出国门，在全球互联网IT舞台上扮演主角，与谷歌比技术，与亚马逊争市场，与facebook赛创意，让世界各地各种文化背景的消费者都可以享受另一个wonderful公司提供的another choice。

看上去要做的这些APP，需要一套好的前端框架。[Vue](https://cn.vuejs.org/) 是一套用于构建用户界面的渐进式框架。与其它大型框架不同的是，Vue 被设计为可以自底向上逐层应用。Vue 的核心库只关注视图层，不仅易于上手，还便于与第三方库或既有项目整合。另一方面，当与现代化的工具链以及各种支持类库结合使用时，Vue 也完全能够为复杂的单页应用提供驱动。

**Comment by haoxiuwang** [comment]
thanks
