### ISSUE TITLE
一点小建议，祝您成功

### ISSUE THREAD

**Issue by amorist** [aomoxo/aomoxo-plan#5]
> 爱梦想将会与腾讯公司为邻，推出可以与微信、QQ相媲美，能够广为人们喜爱的新型聊天软件，让人们从使用不同的产品中体验到不同的喜悦；爱梦想也将会与阿里巴巴比肩，推出敢于与淘宝天猫一争高低的网上购物环境，让购物者在互联网上也同样可以实现多样化的选择，能够刚走出一家商场的大门，立刻就可以踏入另一家一样wonderful的购物中心；爱梦想还会走出国门，在全球互联网IT舞台上扮演主角，与谷歌比技术，与亚马逊争市场，与facebook赛创意，让世界各地各种文化背景的消费者都可以享受另一个wonderful公司提供的another choice。

看上去要做的这些APP，需要既厉害及帅气的大佬 ， 我们应该想要一位在技术方面很有见地的大佬，这里隆重推荐国产程序猿[amorist](https://github.com/amorist)

amorist是一位有多年编程经验，并且能一个经验用多年的大佬，是您创业路上不可缺少的合作伙伴。

**Comment by haoxiuwang** [comment]
thanks
