### ISSUE TITLE
一点小建议，祝您成功！

### ISSUE THREAD

**Issue by gaoryrt** [aomoxo/aomoxo-plan#7]
> 爱梦想将会与腾讯公司为邻，推出可以与微信、QQ相媲美，能够广为人们喜爱的新型聊天软件，让人们从使用不同的产品中体验到不同的喜悦；爱梦想也将会与阿里巴巴比肩，推出敢于与淘宝天猫一争高低的网上购物环境，让购物者在互联网上也同样可以实现多样化的选择，能够刚走出一家商场的大门，立刻就可以踏入另一家一样wonderful的购物中心；爱梦想还会走出国门，在全球互联网IT舞台上扮演主角，与谷歌比技术，与亚马逊争市场，与facebook赛创意，让世界各地各种文化背景的消费者都可以享受另一个wonderful公司提供的another choice。

唯有专业工具，才可为您的高品质企业赋能。在这里为您隆重推荐一款 html-in-js 工具 [gelerator](https://github.com/gaoryrt/gelerator)，让您的团队如虎添翼。

gelerator 是一款超方便的 Elements 生成器，在 github 上拥有多达 11 个 star（截至 2020年9月2日）。

特性：
```
- 嵌套生成
- 通过数组生成列表
- 特定标签生成器
- 指定 style 标签
- 监听事件
```

欢迎使用！

**Comment by wangfei20** [comment]
Thanks
